# For more information: https://laravel.com/docs/sail
version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - db
            - redis
            - meilisearch
            - minio
        ports:
            - '80:80'
            - '443:443'
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: postgres
            POSTGRES_DB: thathrow
        ports:
            - "5432:5432"
        networks:
            - sail
        volumes:
            -   'sail-postgres:/var/lib/postgresql/data'
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '7700:7700'
        volumes:
            - 'sail-meilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
        environment:
            MEILI_MASTER_KEY: masterKey
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - sail
    minio:
        networks:
            - sail
        image: quay.io/minio/minio:RELEASE.2022-07-24T01-54-52Z
        command: server --console-address ":9001" /data1
        expose:
            - "9000"
            - "9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3
        volumes:
            - data1-1:/data1
            - data1-2:/data2
networks:
    sail:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    data1-1:
        driver: local
    data1-2:
        driver: local
